name: 'Push directory to repository'
description: 'Push a directory in this repository to the root of another repository'
inputs:
  source-directory:
    description: 'Source directory from the origin directory'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-directory }}

branding:
  icon: 'git-commit'
  color: 'green'
